version: '3'


services:

  app:
    build: 
      context: .
      dockerfile: Dockerfile
      target: ${STAGE}
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    container_name: nest-app
    ports:
      - ${PORT_SERVER}:${PORT_CONTAINER}
    environment:
      APP_VERSION: ${APP_VERSION}
      STAGE: ${STAGE}
      PORT_SERVER: ${PORT_SERVER}
      PORT_CONTAINER: ${PORT_CONTAINER}
  
  
